
service: ud-2-product-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions: ${file(yml/lambda.yml)}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true

package:
 individually: true

resources: 
  - ${file(yml/table.yml)}
  - ${file(yml/cognito.yml)}
  - ${file(yml/ssm.yml)}


