
service: ud-2-product-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  createProduct:
    handler: src/handler.createProduct
    role: ${env:IAM_ROLE} 
    events:
      - http:
          method: post
          path: product

  updateProduct:
    handler: src/handler.updateProduct
    role: ${env:IAM_ROLE}
    events:
      - http:
          method: put
          path: product/{id}

  deleteProduct:
    handler: src/handler.deleteProduct
    role: ${env:IAM_ROLE}
    events:
      - http:
          method: delete
          path: product/{id}

  getAllProducts:
    handler: src/handler.getAllProducts
    role: ${env:IAM_ROLE}
    events:
      - http:
          method: get
          path: product

  getProduct:
    handler: src/handler.getProduct
    role: ${env:IAM_ROLE}
    events:
      - http:
          method: get
          path: product/{id}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true

package:
 individually: true

resources:
  Resources:
    productTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME}  
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH

