
service: ud-2-product-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  createProduct:
    handler: handler.createProduct
    role: ${env:IAM_ROLE} 
    events:
      - http:
          method: post
          path: product

plugins:
  - serverless-offline

useDotenv: true

package:
 individually: true

resources:
  Resources:
    productTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME}  
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH

