
service: ud-2-product-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  createProduct:
    handler: handler.createProduct
    environment:
      PRODUCT_TABLE_NAME: !Ref productTable
    role: arn:aws:iam::583774065306:role/ud-1-lambda-role
    events:
      - http:
          method: post
          path: product

plugins:
  - serverless-offline

package:
 individually: true

resources:
  Resources:
    productTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH

